namespace :db_populate do
  desc "This task populates the database"
  task create_subjects: :environment do

    data = {"Biologia":{
    "Biologia I - Desenvolvimento e Morfofisiologia Humana":[
    "Origem da Vida: embriologia e desenvolvimento (reprodução - tipos; fecundação - tipos; desenvolvimento embrionário - tipos).",
    "Embriologia geral – segmentação, gástrula e histo & organogêse (o desenvolvimento do embrião)",
    "Embriologia humana - tipos de desenvolvimento embrionário em mamíferos > humanos; nidação e outras etapas do feto; embrião e desenvolvimento - tecidos",
    "Tecido epitelial",
    "Tecidos conjuntivos I – T.C.P.D., Tecidos hematopoiético e adiposo",
    "Tecidos conjuntivos II – Tecidos cartilaginoso e ósseo (ossificação endocondral - link osteichthyes)",
    "Tecidos conjuntivos III – Tecido sanguíneo",
    "Tecido muscular – Muscular liso, muscular estriado esquelético e estriado cardíaco",
    "Tecido Nervoso",
    "Sistema digestório humano",
    "Sistema respiratório humano",
    "Sistema cardiovascular humano",
    "Sistema linfático e imunológico I",
    "Sist. Imune II: Vacinas e soros",
    "Sistema excretor humano",
    "Sistema endócrino I – Hipófise",
    "Sistema endócrino II – tireoide, paratireoide e suprarrenal",
    "Sistema nervoso I: SNC",
    "Sistema Nervoso II: SNP",
    "Sistema Sensorial I",
    "Sistema Nervoso e Sensorial juntos: comportamento humano",
    "Sistema reprodutor I - masculino",
    "Sistema reprodutor II - feminino",
    "Reprodução Humana: genética do sexo",
    "Reprodução Humana: sexualidade e diversidade sexual EXTRA?"],
    
    "Biologia II - Evolução & Seres Vivos I":[
    "Origem da Vida - abiogenese x biogenese; 'primeiro ser vivo' - intercalado com experimentos (pasteur, fox e miller, urey, redi); (coacervatos: características básicas) - eu x procariontes; evolução breve",
    "Metodologia Científica",
    "Ideias Evolutivas (de Lamarck a Darwin) - tempo geológico!",
    "Teoria Sintética da Evolução",
    "Vírus (o que é vida)",
    "Bactérias",
    "Protozoários",
    "Fungos",
    "As características e a classificação dos animais (taxonomia e sistemática filogenética)",
    "Poríferos",
    "Cnidários",
    "Platelmintos",
    "Nematódeos",
    "Moluscos",
    "Anelídeos",
    "Arthropoda I (não-Hexapoda)",
    "Arthropoda II (Hexapoda)",
    "Equinodermos (Hemi e Protochordata)",
    "Intro Chordata + Chondrichthyes",
    "Peixes e a saída da água",
    "Anfíbios",
    "Répteis",
    "Aves",
    "Mamíferos",
    "Evolução Humana: Homo sapiens roboticus"],
    
    "Biologia III - Bioquímica & Genética":[
    "Origem da vida: o solvente universal (a água - carac., quimica, polaridade, metabolismo, temperatura, OSMOSE!)",
    "Componentes químicos dos seres vivos: sais minerais",
    "Componentes químicos dos seres vivos: carboidratos",
    "Componentes químicos dos seres vivos: lipídios",
    "Componentes químicos dos seres vivos: proteínas",
    "Componentes químicos dos seres vivos: proteínas especiais (enzimas)",
    "Componentes químicos dos seres vivos: vitaminas lipo e hidrossolúveis",
    "Introdução à Citologia (célula animal e vegetal; tipos de células)",
    "Membranas e Paredes celulares: tipos, estruturas e modificações da membrana",
    "Membranas e Paredes celulares: fisiologia da membrana e transportes",
    "Estudo do citoplasma: visão geral, hialoplasma e citoesqueleto",
    "Organelas I: ribossomos, retículo endoplasmático e complexo golgiense",
    "Organelas II: lisossomos, peroxissomos, glioxissomos, hidrogenossomos, plastos e mitocôndrias",
    "Respiração celular I: glicólise e fermentações",
    "Respiração celular II: ciclo de Krebs, cadeia respiratória e fosforilação oxidativa",
    "Fotossíntese: etapas detalhadas da respiração",
    "Fotossíntese: fatores que influenciam e quimiossintese",
    "Estudo do núcleo: ácidos nucleicos (DNA e RNA)",
    "Ciclo celular: mitose & meiose",
    "Introdução à genética",
    "1ª lei de mendel",
    "2ª lei de mendel",
    "Alelos múltiplos e grupos sanguíneos",
    "Mutações",
    "Engenharia genética: biotecnologia"],
    
    "Biologia IV - Ecologia & Seres Vivos II":[
    "Origem da vida: evolução (volvox) e introdução à botânica",
    "Algas e cianobactérias",
    "Briófitas e Pteridófitas",
    "Gimnospermas",
    "Angiospermas",
    "Histologia vegetal",
    "Morfologia vegetal – Raiz",
    "Morfologia vegetal – Caule",
    "Respiração: aspectos gerais da fotossíntese",
    "Fisiologia vegetal: Absorção, condução de seivas e transpiração",
    "Fisiologia vegetal: Hormônios vegetais",
    "Reprodução: ciclos reprodutivos (interação 'inseto'-planta)",
    "Botânica Econômica",
    "Introdução à Ecologia",
    "Ciclos Biogeoquímicos: nitrogênio",
    "Ciclos Biogeoquímicos: carbono",
    "Ciclos Biogeoquímicos: água e oxigênio",
    "Fluxo de energia e pirâmides ecológicas",
    "Relações ecológicas",
    "Sucessão ecológica",
    "Dinâmica populacional",
    "Especiação & Biodiversidade",
    "Genética de Populações",
    "Desequilíbrios ecológicos (pandemias)",
    "Mudanças Climáticas e atualidades"]
    },
    
    "Matemática":{
    "Matemática I":[
    "Noções de Lógica",
    "Conjuntos",
    "Conjuntos Numéricos",
    "Sistemas de Numeração",
    "Operação nos Inteiros, Operações nos Reais, Potenciação nos Reais, Radiciação nos Reais",
    "Produtos Notáveis e Fatoração",
    "Intervalos Reais e Inequações",
    "Razões e Proporções, Números Proporcionais e Grandezas Proporcionais",
    "Função Exponencial",
    "Logaritmos",
    "Função logarítmica",
    "Equações exponenciais e logarítmicas",
    "Logaritmos decimais",
    "Inequações exponenciais e logarítmicas",
    "Sequências",
    "Progressão Aritmética",
    "Progressão Geométrica",
    "Números Complexos",
    "Polinômios",
    "Matrizes",
    "Determinantes",
    "Sistemas Lineares"],
    
    "Matemática II":[
    "Relações",
    "Introdução às Funções",
    "Funções Constante e Afim",
    "Função Quadrática",
    "Função Modular",
    "Outras Funções",
    "Função Composta - Função Inversa",
    "Equações Irracionais",
    "Inequações Irracionais",
    "Trigonometria no triângulo retângulo",
    "Razões trigonométricas no triângulo retângulo",
    "Arcos e ângulos",
    "Razões trigonométricas na circunferência",
    "Relações fundamentais",
    "Arcos notáveis",
    "Redução ao 1 o quadrante",
    "Funções trigonométricas: Funções circulares",
    "Transformações",
    "Identidades",
    "Equações",
    "Inequações",
    "Funções circulares inversas",
    "APÊNDICE B => Trigonometria em triângulos quaisquer",
    "Coordenadas Caresianas no Plano",
    "Equação da Reta",
    "Teoria Angular",
    "Distância de Ponto a Reta",
    "Circunferências",
    "Problemas sobre circunferências",
    "Cônicas",
    "Lugares Geométricos"],
    
    "Matemática III":[
    "Introdução à combinatória, Fatorial",
    "Princípio Fundamental da Contagem, Permutações Simples",
    "Permutações com elementos repetidos",
    "Permutações circulares",
    "Permutações caóticas",
    "Arranjos e combinações",
    "Combinações completas",
    "Probabilidades (Definição)",
    "Probabilidades com união e Intersecção de eventos",
    "Probabilidade condicional",
    "Eventos independentes",
    "Distribuição Binomial de Probabilidades",
    "Eventos não equiprováveis",
    "Eventos Complementares",
    "Probabilidade Geométrica",
    "Matemática Comercial",
    "Matemática Financeira",
    "Estatística Descritiva I",
    "Estatística Descritiva II"],
    
    "Matemática IV":[
    "Noções e Proposições Primitivas, segmento de reta, ângulos",
    "Triângulos",
    "Paralelismo, Perpendicularidade",
    "Quadriláteros Notáveis",
    "Pontos Notáveis do Triângulo",
    "Polígonos",
    "Circunferência, Ângulos na Circunferência e Comprimento da Circunferência",
    "Teorema de Tales",
    "Semelhança de Triângulos e Potência de Ponto",
    "Triangulos Retângulos",
    "Triângulos Quaisquer",
    "Polígonos Regulares",
    "Areas de Superfícies Planas",
    "Noções e Proposições Primitivas (Geometria Espacial)",
    "Paralelismo e Perpendicularidade",
    "Aplicações (Esse tópico deverá ser olhado no FME, porque são diversos sub-tópicos aparentemente desconexos)",
    "Diedros e Triedros",
    "Poliedros Convexos",
    "Prisma",
    "Pirâmide",
    "Cilíndro",
    "Cone",
    "Esfera",
    "Sólidos Semelhantes – Troncos",
    "Inscrição e Circunscrição de Sólidos",
    "Superfícies e Sólidos de Revolução",
    "Superfícies e Sólidos Esféricos"]
    },
    
    "Química":{
    
    "Química I":[
    "Introdução à Química Orgânica",
    "Hidrocarbonetos",
    "Petróleo",
    "Funções oxigenadas",
    "Funções nitrogenadas",
    "Outras funções orgânicas",
    "Propriedades físicas dos compostos orgânicos",
    "Isomeria plana ou isomeria constitucional",
    "Isomeria espacial ou Estereoisomeria",
    "Acidez e Basicidade dos compostos orgânicos",
    "Reações orgânicas de adição",
    "Reações orgânicas de eliminação",
    "Reações orgânicas de substituição",
    "Reações orgânicas de oxidação e redução",
    "Polímeros",
    "Biomoléculas"],
    
    "Química II":[
    "Termoquímica – noções de entalpia",
    "Termoquímica – fatores que influenciam no ΔH; ΔHs importantes",
    "Termoquímica – Lei de Hess",
    "Termoquímica – Entalpia de ligação",
    "Estudo das soluções – classificação e solubilidade",
    "Curvas de solubilidade",
    "Unidades de concentração",
    "Diluição de soluções",
    "Mistura de soluções sem reação química",
    "Propriedades coligativas",
    "Cinética Química – conceito de velocidade de reação",
    "Cinética Química – teoria das colisões e do complexo ativado",
    "Cinética Química – leis de velocidade e ordens de reação",
    "Cinética Química – fatores que influenciam na velocidade",
    "Equilíbrio químico – noções de equilíbrio; cálculos com equilíbrio",
    "Equilíbrio químico – deslocamento do equilíbrio",
    "Equilíbrio iônico – pH e pOH",
    "Equilíbrio iônico – ácidos e bases; lei da diluição; efeito do íon comum",
    "Equilíbrio iônico – hidrólise de sais",
    "Equilíbrio iônico – solução tampão",
    "Produto de solubilidade"],
    
    "Química III":[
    "Grandezas químicas",
    "Cálculo de fórmulas",
    "Cálculo estequiométrico I: casos gerais",
    "Cálculo estequiométrico II: casos especiais",
    "Teoria Cinética, Leis empíricas dos gases",
    "A equação de estado do gás ideal e densidade",
    "Efusão e mistura de gases",
    "Oxidação e redução",
    "Balanceamento por oxirredução",
    "Estudo dos ácidos",
    "Estudo das bases",
    "Conceitos modernos sobre ácidos e bases",
    "Estudo dos sais",
    "Estudo dos óxidos",
    "Reações inorgânicas I",
    "Química ambiental",
    "Propriedades da matéria",
    "Substâncias e Misturas",
    "Análise imediata e materiais de laboratório"],
    
    "Química IV":[
    "As primeiras ideias sobre átomos e a natureza da matéria",
    "Modelo atômico de Rutherford e os conceitos fundamentais",
    "Teoria quântica e o modelo de Böhr",
    "Números quânticos e configurações eletrônicas",
    "Classificação periódica",
    "Tendências periódicas",
    "Ligações químicas – iônica, metálica e covalente",
    "Fórmulas de Lewis",
    "Geometria molecular",
    "Hibridação de orbitais",
    "Polaridade de ligações e moléculas",
    "Forças intermoleculares",
    "Radioatividade",
    "Coloides",
    "Eletroquímica – pilhas e ddp",
    "Eletroquímica – força oxidante, redutora e pilhas comerciais",
    "Eletroquímica – corrosão e proteção de metais",
    "Eletroquímica – eletrólise ígnea com eletrodos inertes",
    "Eletroquímica – eletrólise aquosa com eletrodos inertes",
    "Eletroquímica – eletrólise com eletrodos ativos",
    "Eletroquímica – estequiometria da eletrólise"]
    },
    
    "Física":{
    
    "Física I":[
    "Movimento Uniforme",
    "Movimento Variado",
    "Queda Livre",
    "Movimento Circular",
    "Vetores",
    "Leis de Newton",
    "Força Elástica",
    "Força de Atrito",
    "Dinâmica do Movimento Circular",
    "Trabalho e Potência",
    "Energia",
    "Impulso e Quantidade de Movimento",
    "Colisões"],
    
    "Física II":[
    "Carga Elétrica",
    "Processos de Eletrização",
    "Força elétrica – Lei de Coulomb",
    "Campo Elétrico",
    "Potencial Elétrico",
    "Condutor Esférico",
    "Corrente Elétrica",
    "Potência Elétrica",
    "Resistores(Leis 1 e 2 de Ohm)",
    "Associação de Resistores",
    "Instrumentos de Medida",
    "Gerador Elétrico",
    "Potência Elétrica do Gerador",
    "Receptor Elétrico",
    "Associação de Geradores e Receptores",
    "Leis de Kirchhoff",
    "Capacitor",
    "Introdução ao Magnetismo",
    "Fontes de Campo Magnético",
    "Força Magnética",
    "Indução Magnética"],
    
    "Física III":[
    "Energia Térmica e Escalas Termométricas",
    "Dilatação dos Sólidos e Líquidos",
    "Energia Interna Sensível",
    "Sistemas Termicamente Isolados",
    "Energia Interna Latente",
    "Influência da Pressão na Mudança de Fase",
    "Meios de Propagação do Calor",
    "Gases Perfeitos",
    "Cinética dos Gases",
    "Primeira Lei da Termodinâmica e Aplicações",
    "Máquinas Térmicas: Motores e Refrigeradores",
    "Reversibilidade, Entropia e Ciclo de Carnot",
    "Movimentos Harmônico Simples",
    "Ondas",
    "Fenômenos Ondulatórios",
    "Fenômenos Ondulatórios e Interferência",
    "Interferência",
    "Acústica",
    "Fenômenos Sonoros e Instrumentos Musicais",
    "Efeito Doppler"],
    
    
    "Física IV":[
    "Introdução à Óptica Geométrica",
    "Espelhos Planos",
    "Espelhos Esféricos",
    "Refração",
    "Reflexão Total, ângulo Limite, Dioptro Plano e Lâminas de Faces Paralelas",
    "Prismas",
    "Lentes Esféricas",
    "Instrumentos Ópticos",
    "Óptica da Visão",
    "Estática de um Ponto Material e de um Corpo Extenso",
    "Máquinas Simples e Centro de Massa",
    "Hidrostática(Teoremas de Stevin,Pascal e Arquimedes)",
    "Leis de Kepler",
    "Lei da Gravitação Universal e Campo Gravitacional",
    "Velocidade Orbital e Velocidade de Escape",
    "Revisão de Gravitação"]
    }
    }

    puts "Creating course ENEM..."
    course = Course.create(name: "ENEM")

    data.each do |field_name, subjects|
      puts " - Creating field %s..." % [field_name]
      field = Field.create(name: field_name, course: course)

      subjects.each do |subject_name, lessons_array|
        puts " - - Creating subject %s..." % [subject_name]
        subject = Subject.create(name: subject_name, field: field)

        puts " - - - Creating %d lessons" % [lessons_array.length]
        lessons_array.each do |lesson_name|
          # slower than insert_all, but this is performed once
          lesson = Lesson.create(name: lesson_name, subject: subject)
        end
      end
    end
  

  end

end
